version: '3.8'

services:
  # Serviço PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: seug-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: seug
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 644004
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d seug"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  # Serviço da aplicação
  seug-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seug-sistema
    restart: unless-stopped
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=644004
      - DB_DATABASE=seug
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
    driver: local 